"""initial_schema

Revision ID: 8b17ee53ad27
Revises: 
Create Date: 2026-09-12 19:07:12.889200

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b17ee53ad27'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('entity_type', sa.String(length=64), nullable=False, comment='Table/domain name: incident, plan, task, resource, …'),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('action', sa.String(length=64), nullable=False, comment='created | updated | assigned | completed | replanned | escalated | …'),
    sa.Column('actor', sa.String(length=128), nullable=False, comment="Agent name, user ID, or 'system'"),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_logs_created_at', 'audit_logs', ['created_at'], unique=False)
    op.create_index('ix_audit_logs_entity', 'audit_logs', ['entity_type', 'entity_id'], unique=False)
    op.create_table('incidents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False, comment='open | in_progress | resolved | closed'),
    sa.Column('severity', sa.String(length=16), nullable=False, comment='low | medium | high | critical'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('locations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('population', sa.Integer(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('current_status', sa.String(length=64), nullable=False, comment='normal | affected | evacuated | sheltering'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('policies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('action_type', sa.String(length=64), nullable=False, comment='assign_resource | reassign_resource | evacuate | notify | mark_duplicate | …'),
    sa.Column('max_impact_scope', sa.String(length=64), nullable=True, comment='single_resource | single_location | multi_location | city_wide'),
    sa.Column('requires_human', sa.Boolean(), nullable=False),
    sa.Column('auto_approve_conditions', sa.JSON(), nullable=True, comment='JSON conditions under which the action can proceed without human review'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('action_type')
    )
    op.create_table('events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('incident_id', sa.UUID(), nullable=True),
    sa.Column('event_type', sa.String(length=64), nullable=False, comment='report | sensor | update | alert | resolution'),
    sa.Column('source', sa.String(length=128), nullable=False, comment='Origin of the event: citizen_report, iot_sensor, official_update, …'),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('location_id', sa.UUID(), nullable=True),
    sa.Column('severity', sa.String(length=16), nullable=False, comment='low | medium | high | critical'),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('dedup_key', sa.String(length=128), nullable=True, comment='Composite dedup hash to prevent duplicate event ingestion'),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dedup_key')
    )
    op.create_index('ix_events_created_at', 'events', ['created_at'], unique=False)
    op.create_index('ix_events_dedup_key', 'events', ['dedup_key'], unique=True)
    op.create_index('ix_events_incident_id', 'events', ['incident_id'], unique=False)
    op.create_table('plans',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('incident_id', sa.UUID(), nullable=False),
    sa.Column('goal', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False, comment='draft | active | completed | failed | superseded'),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True, comment='Why this plan was created or why it replaced a prior version'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('approved_by', sa.String(length=128), nullable=True),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('resources',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('resource_type', sa.String(length=64), nullable=False, comment='water_tanker | generator | medical_kit | food_supply | shelter | vehicle | …'),
    sa.Column('status', sa.String(length=32), nullable=False, comment='available | assigned | in_transit | depleted | maintenance'),
    sa.Column('capacity', sa.Integer(), nullable=True),
    sa.Column('location_id', sa.UUID(), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('teams',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('team_type', sa.String(length=64), nullable=False, comment='medical | logistics | search_rescue | communication | water | shelter'),
    sa.Column('status', sa.String(length=32), nullable=False, comment='available | deployed | standby | off_duty'),
    sa.Column('location_id', sa.UUID(), nullable=True),
    sa.Column('capacity', sa.Integer(), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tasks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('plan_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False, comment='pending | in_progress | completed | failed | blocked'),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('assigned_resource_id', sa.UUID(), nullable=True),
    sa.Column('assigned_team_id', sa.UUID(), nullable=True),
    sa.Column('requires_human', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['assigned_resource_id'], ['resources.id'], ),
    sa.ForeignKeyConstraint(['assigned_team_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('assignments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('resource_id', sa.UUID(), nullable=True),
    sa.Column('team_id', sa.UUID(), nullable=True),
    sa.Column('task_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False, comment='pending | active | completed | cancelled'),
    sa.Column('assigned_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['resource_id'], ['resources.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('decisions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('task_id', sa.UUID(), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('options', sa.JSON(), nullable=True, comment='JSON array of option strings or objects'),
    sa.Column('selected_option', sa.String(length=255), nullable=True),
    sa.Column('decided_by', sa.String(length=128), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('decisions')
    op.drop_table('assignments')
    op.drop_table('tasks')
    op.drop_table('teams')
    op.drop_table('resources')
    op.drop_table('plans')
    op.drop_index('ix_events_incident_id', table_name='events')
    op.drop_index('ix_events_dedup_key', table_name='events')
    op.drop_index('ix_events_created_at', table_name='events')
    op.drop_table('events')
    op.drop_table('policies')
    op.drop_table('locations')
    op.drop_table('incidents')
    op.drop_index('ix_audit_logs_entity', table_name='audit_logs')
    op.drop_index('ix_audit_logs_created_at', table_name='audit_logs')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
